{
 "title": "FastStream Metrics",
 "description": "FastStream is a powerful and easy-to-use Python framework for building asynchronous services interacting with event streams such as Apache Kafka, RabbitMQ, NATS and Redis",
 "tags": [ "faststream" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "metrics_prefix", "label": "Metrics Prefix", "query": "faststream" },
   { "name": "app_name", "label": "App Name", "query": { "query": "label_values(app_name)" } },
   {
    "name": "destination",
    "label": "Destination",
    "query": {
     "query": "label_values({__name__=~\"${metrics_prefix}_published_messages_total\", app_name=~\"$app_name\"},destination)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values({__name__=~\"${metrics_prefix}_received_messages_total\", app_name=~\"$app_name\"},handler)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total messages published",
   "type": "stat",
   "description": "All published messages of all statuses for the interval",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_total\", destination=~\"$destination\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Messages published",
   "type": "stat",
   "description": "The number of successfully published messages per destination in the interval",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_total\", status=\"success\", destination=~\"$destination\"} [$__range])",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Total messages received",
   "type": "stat",
   "description": "All received messages of all statuses for the interval",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_total\", handler=~\"$handler\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Total messages processed",
   "type": "stat",
   "description": "All processed messages of all statuses for the interval",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", handler=~\"$handler\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Messages processed",
   "type": "stat",
   "description": "The number of acked messages per handler in the interval",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"acked\", handler=~\"$handler\"} [$__range])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Publish exceptions",
   "type": "stat",
   "description": "All publication errors in the interval",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_exceptions_total\", destination=~\"$destination\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Publish average duration",
   "type": "bargauge",
   "description": "The average time of the publication duration for all messages per interval",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_duration_seconds_sum\", destination=~\"$destination\"} / {app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_duration_seconds_count\", destination=~\"$destination\"}",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Process exceptions",
   "type": "stat",
   "description": "All process errors in the interval",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_exceptions_total\", handler=~\"$handler\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Messages in progress",
   "type": "stat",
   "description": "The number of messages in the process",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_in_process\", handler=~\"$handler\"})"
    }
   ]
  },
  {
   "title": "Process average duration",
   "type": "bargauge",
   "description": "The average processing time for all messages per interval",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_duration_seconds_sum\", handler=~\"$handler\"} / {app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_duration_seconds_count\", handler=~\"$handler\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Publish per sec",
   "type": "timeseries",
   "description": "Publishing messages per second with the status",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_total\", destination=~\"$destination\"} [1m])",
     "legendFormat": "{{destination}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Process per sec",
   "type": "timeseries",
   "description": "Processing messages per second with the status",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", handler=~\"$handler\"} [1m])",
     "legendFormat": "{{handler}} [{{status}}]"
    }
   ]
  },
  {
   "title": "Messages in process",
   "type": "timeseries",
   "description": "Messages in process",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "{app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_in_process\", handler=~\"$handler\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Publish duration [PR 99]",
   "type": "timeseries",
   "description": "The longest message publishing",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_published_messages_duration_seconds_bucket\", destination=~\"$destination\"} [1m])) by(destination, le))",
     "legendFormat": "{{destination}}"
    }
   ]
  },
  {
   "title": "Process duration [PR 99]",
   "type": "timeseries",
   "description": "The longest message processing",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_duration_seconds_bucket\", handler=~\"$handler\"} [1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Received message size [PR 99]",
   "type": "timeseries",
   "description": "The largest received messages in size",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_messages_size_bytes_bucket\", handler=~\"$handler\"} [1m])) by(handler, le))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percentages of processed message statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "Percent of acked messages",
   "type": "timeseries",
   "description": "Percentage of acked messages relative to all messages",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"acked\", handler=~\"$handler\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", handler=~\"$handler\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of error messages",
   "type": "timeseries",
   "description": "Percentage of error messages relative to all messages",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=\"error\", handler=~\"$handler\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", handler=~\"$handler\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Percent of nacked, rejected, skipped messages",
   "type": "timeseries",
   "description": "Percentage of nacked, rejected, skipped messages relative to all messages",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", status=~\"nacked|rejected|skipped\", handler=~\"$handler\"}) / sum by(handler) ({app_name=~\"$app_name\", __name__=~\"${metrics_prefix}_received_processed_messages_total\", handler=~\"$handler\"})",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}